feat: add vertifybamid2
hydra-genetics/qc pull request #108
Opened 2023-10-06 12:22 UTC by MagdalenaZZ

### This PR:

(If this is a release PR, no need to add following. Leave this part empty)
(Use the following lines to create a PR text body. Make sure to remove all non-relevant one after you're done)
(Repeat each field as many times as necessary)

Added: for new features.
Changed: for changes in existing functionality.
Deprecated: for soon-to-be removed features.
Removed: for now removed features.
Fixed: for any bug fixes.
Security: in case of vulnerabilities.

### Review and tests:
- [ ] Tests pass
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Code review
- [ ] `CHANGELOG.md` is updated
- [ ] New code is executed and covered by tests, and test approve
- [ ] Module compatibility section in `README.md` is up to date

2023-10-06 13:06 UTC, elleira approved these changes

2023-10-06 13:39 UTC, jonca79 requested changes

2023-10-06 13:39 UTC, jonca79 commented on docs/softwares.md
> +Introduction to verifybamid2
Write short description here

2023-10-06 13:39 UTC, jonca79 commented on .tests/integration/verifybamid2/1000g.phase3.10k.b38.exome.vcf.gz.dat.UD
Remove these test files?

2023-10-09 13:49 UTC, MagdalenaZZ reviewed
Thanks @jonca79 for the review - I've tried to address all the points you mentioned.

2023-10-09 13:49 UTC, MagdalenaZZ commented on docs/softwares.md
> +<<<<<<< HEAD
Line removed, well spotted :-D)

2023-10-09 13:49 UTC, MagdalenaZZ commented on docs/softwares.md
> +Introduction to verifybamid2
Added software description.

2023-10-09 13:49 UTC, MagdalenaZZ commented on workflow/schemas/rules.schema.yaml
> + mosdepth:
Indentation fixed

2023-10-09 14:03 UTC, merged